"use client";

import { useActionState } from "react";
import { updateScheduleAction, type ActionState } from "@/src/application/web-actions";

export function SettingsForm({ schedule }: { schedule: { enabled: boolean; timezone: string; weekday: number; hour: number; minute: number; catchUpHours: number; seeds: string[] } }) {
  const [state, formAction, pending] = useActionState(updateScheduleAction, {} as ActionState);
  return <form className="settings-form" action={formAction}><div className="field-wide checkbox-field"><input id="enabled" name="enabled" type="checkbox" defaultChecked={schedule.enabled} /><label htmlFor="enabled">Enable weekly schedule</label></div><div><label htmlFor="timezone">Timezone</label><input id="timezone" name="timezone" defaultValue={schedule.timezone} /></div><div><label htmlFor="weekday">Weekday</label><select id="weekday" name="weekday" defaultValue={schedule.weekday}><option value="1">Monday</option><option value="2">Tuesday</option><option value="3">Wednesday</option><option value="4">Thursday</option><option value="5">Friday</option><option value="6">Saturday</option><option value="0">Sunday</option></select></div><div><label htmlFor="hour">Hour</label><input id="hour" name="hour" type="number" min="0" max="23" defaultValue={schedule.hour} /></div><div><label htmlFor="minute">Minute</label><input id="minute" name="minute" type="number" min="0" max="59" defaultValue={schedule.minute} /></div><div><label htmlFor="catchUpHours">Catch-up window, hours</label><input id="catchUpHours" name="catchUpHours" type="number" min="0" max="168" defaultValue={schedule.catchUpHours} /></div><div className="field-wide"><label htmlFor="seeds">Weekly seed URLs <span className="field-help">one per line</span></label><textarea id="seeds" name="seeds" defaultValue={schedule.seeds.join("\n")} placeholder="https://berlinflow.example" /></div><div className="settings-actions"><button className="button button-primary" type="submit" disabled={pending}>{pending ? "Saving..." : "Save schedule"}</button>{state.error && <span className="form-error" role="alert">{state.error}</span>}{!state.error && !pending && <span>Scheduling stays off until you enable it and run the launch checks.</span>}</div></form>;
}
