import Link from "next/link";
import { notFound } from "next/navigation";
import { getRunReadModel } from "@/src/application/read-models";
import { BackLink, ButtonLink, EmptyState, PageHeading, SectionHeading, ScoreMark, StatusBadge, formatDate, formatDateTime, isStale, SourceCitation } from "@/src/ui/components";
import { Icon } from "@/src/ui/icons";

export const dynamic = "force-dynamic";

export default async function RunReportPage({ params }: { params: Promise<{ runId: string }> }) {
  const { runId } = await params;
  const data = await getRunReadModel(runId);
  if (!data) notFound();
  const passing = data.companies.flatMap((row) => row.opportunities.filter((opportunity) => opportunity.gate?.passed && opportunity.scorecard));
  const rejected = data.companies.flatMap((row) => row.opportunities.filter((opportunity) => opportunity.gate && !opportunity.gate.passed));
  return (
    <main className="page-shell">
      <BackLink href={`/scout-runs/${runId}`}>Scout Run {runId.slice(0, 8)}</BackLink>
      <PageHeading title="Weekly report" description={<>A concise shortlist from the {formatDate(data.run.createdAt)} run. Every proposal remains one click away from its evidence.</>} action={<ButtonLink href={`/scout-runs/${runId}`} variant="secondary"><Icon name="pulse" size={15} />Run detail</ButtonLink>} />
      <div className="stat-strip" aria-label="Report summary"><div className="stat-cell"><span className="stat-value">{passing.length}</span><span className="stat-label">shortlist candidates</span></div><div className="stat-cell"><span className="stat-value">{data.companies.length}</span><span className="stat-label">company lanes</span></div><div className="stat-cell"><span className="stat-value">{data.run.actualCostEur} EUR</span><span className="stat-label">actual spend</span></div><div className="stat-cell"><span className="stat-value">{data.run.status === "succeeded" ? "complete" : "partial"}</span><span className="stat-label">run outcome</span></div></div>
      {data.run.degradationWarnings.length > 0 && <div className="callout callout-warning"><h3>Read with limitations</h3>{data.run.degradationWarnings.map((warning) => <p key={warning}>{warning}</p>)}</div>}
      <section className="run-list" aria-labelledby="shortlist-title"><SectionHeading title="Top opportunities" detail="At most three primary opportunities are intended for the weekly review." action={<span>{passing.length} passed gate</span>} />{passing.length ? <div className="attention-list report-list">{passing.slice(0, 3).map((row) => <article className="attention-item" key={row.opportunity.id}><Link href={`/opportunities/${row.opportunity.id}`}><div className="item-meta"><StatusBadge value={row.opportunity.rankingConfidence} tone="info" /><span>{row.company.canonicalName}</span></div><h3>{row.opportunity.proposedSystem}</h3><p>{row.hypothesis.painHypothesis}</p><div className="attention-foot"><ScoreMark score={row.scorecard?.totalScore} confidence={row.opportunity.rankingConfidence} /><small>next: {row.opportunity.nextValidationStep}</small></div></Link></article>)}</div> : <EmptyState title="No shortlist this run" description="The correct result may be not enough evidence. Inspect the company lanes for the exact stopping reason." />}</section>
      <section className="detail-content report-content"><div className="detail-main"><section className="detail-section"><SectionHeading title="Why these made the cut" detail="The report assembles existing claims. It creates no new facts." />{passing.slice(0, 3).map((row) => <div className="report-entry" key={row.opportunity.id}><div className="report-entry-head"><div><h2><Link href={`/opportunities/${row.opportunity.id}`}>{row.company.canonicalName}</Link></h2><p>{row.opportunity.proposedSystem}</p></div><ScoreMark score={row.scorecard?.totalScore} confidence={row.opportunity.rankingConfidence} /></div><div className="tag-row"><span className="tag">{row.opportunity.evidenceStrength} evidence</span><span className="tag">{row.opportunity.buildability} buildability</span><span className="tag">{row.opportunity.genericnessStatus}</span></div><p className="report-measure"><strong>Measure:</strong> {row.opportunity.measurableOutcome}</p></div>)}</section><section className="detail-section"><SectionHeading title="Interesting, but held" detail="Rejected opportunities stay visible for learning." />{rejected.length ? <ul className="diagnostic-list">{rejected.map((row) => <li key={row.opportunity.id}><Link className="text-link" href={`/opportunities/${row.opportunity.id}`}>{row.company.canonicalName}</Link> · {row.gate?.failureCodes.join(", ")}</li>)}</ul> : <p>No opportunity was rejected by a completed gate.</p>}</section></div><aside className="detail-aside"><section className="panel panel-dark"><div className="panel-header"><div><h2>Run footprint</h2><p>Budget and evidence coverage.</p></div><Icon name="terminal" size={18} /></div><div className="panel-body"><div className="report-footprint"><strong>{data.run.actualCostEur}</strong><span>/ {data.run.maxEur} EUR</span></div><p className="dark-copy">{data.run.actualSearchRequests} search requests · {data.workItems.length} durable work items · {data.run.currentStage.replaceAll("_", " ")}.</p></div></section><section className="detail-section"><SectionHeading title="Source coverage" detail="Freshness is visible, never implied." />{data.companies.flatMap((row) => row.dossier?.sources ?? []).slice(0, 8).map((source) => <SourceCitation key={source.id} url={source.canonicalUrl} title={source.title} tier={source.sourceTier} fetchedAt={source.fetchedAt} stale={isStale(source.fetchedAt)} />)}</section></aside></section>
      <p className="footer-note">Run generated {formatDateTime(data.run.createdAt)}. Research-only output. No outreach or external state changes are available from this report.</p>
    </main>
  );
}
