import Link from "next/link";
import { notFound } from "next/navigation";
import { getOpportunityReadModel } from "@/src/application/read-models";
import { BackLink, EmptyState, EpistemicLabel, EvidenceLine, PageHeading, SectionHeading, SourceCitation, StatusBadge, formatDateTime, isStale } from "@/src/ui/components";
import { ReviewForm } from "@/src/ui/review-form";
import { Icon } from "@/src/ui/icons";
import { opportunityWeights } from "@/src/domain/scoring";

export const dynamic = "force-dynamic";

const dimensionLabels: Record<string, string> = { evidenceStrength: "Evidence strength", painPlausibility: "Pain plausibility", automationLeverage: "Automation leverage", measurability: "Measurability", buildability: "Buildability", differentiation: "Differentiation", portfolioCareerSignal: "Portfolio signal" };

export default async function OpportunityDetailPage({ params }: { params: Promise<{ opportunityId: string }> }) {
  const { opportunityId } = await params;
  const data = await getOpportunityReadModel(opportunityId);
  if (!data) notFound();
  const { opportunity, hypothesis, gate, scorecard, company, dossier, reviews } = data;
  const evidenceLinks = dossier?.evidenceLinks.filter((row) => hypothesis.evidenceItemIds.includes(row.evidence.id)) ?? [];
  const currentDecision = reviews[0]?.decision ?? null;
  return (
    <main className="page-shell">
      <BackLink href="/opportunities">Opportunity ledger</BackLink>
      <PageHeading title={opportunity.proposedSystem} description={<><Link className="text-link" href={`/companies/${company.id}`}>{company.canonicalName}</Link> · {company.canonicalDomain} · generated {formatDateTime(opportunity.createdAt)}</>} />
      <div className="detail-content">
        <div className="detail-main">
          <section className="detail-section" aria-labelledby="evidence-title"><SectionHeading title="Observed evidence" detail="These are the facts this proposal is allowed to use." />{evidenceLinks.length ? evidenceLinks.map((row) => <EvidenceLine key={`${row.evidence.id}-${row.link.claimId}`} claimType={row.link.relation === "supports" ? "verified" : "inferred"} sourceUrl={row.source.canonicalUrl} sourceTitle={row.source.title} sourceTier={row.source.sourceTier} fetchedAt={row.source.fetchedAt} stale={isStale(row.source.fetchedAt)}>{row.evidence.normalizedContent}</EvidenceLine>) : <EmptyState title="No linked evidence" description="This opportunity cannot be trusted without evidence links." />}</section>
          <section className="detail-section" aria-labelledby="hypothesis-title"><SectionHeading title="Workflow hypothesis" detail={`${hypothesis.confidence} confidence · a hypothesis, not an internal fact`} /><p className="lead-copy">{hypothesis.description}</p><div className="fact-grid"><div><span className="queue-label">Actors</span><div className="tag-row">{hypothesis.actors.map((actor) => <span className="tag" key={actor}>{actor}</span>)}</div></div><div><span className="queue-label">Trigger</span><p>{hypothesis.trigger}</p></div></div><h3>Likely steps</h3><ol className="step-list">{hypothesis.likelySteps.map((step) => <li key={step}>{step}</li>)}</ol><h3>Pain hypothesis</h3><p>{hypothesis.painHypothesis}</p>{hypothesis.alternativeExplanation && <div className="callout"><h3>Alternative explanation</h3><p>{hypothesis.alternativeExplanation}</p></div>}</section>
          <section className="detail-section" aria-labelledby="proposal-title"><SectionHeading title="Proposed automation" detail="Ordinary software first. AI only where ambiguity needs interpretation." /><p className="lead-copy">{opportunity.proposedSystem}</p><div className="split-lists"><div><h3>Deterministic steps</h3><ul className="step-list">{opportunity.deterministicSteps.map((step) => <li key={step}><Icon name="check" size={14} />{step}</li>)}</ul></div><div><h3>AI-required steps</h3>{opportunity.aiRequiredSteps.length ? <ul className="step-list">{opportunity.aiRequiredSteps.map((step) => <li key={step}><Icon name="spark" size={14} />{step}</li>)}</ul> : <p>None required by this proposal.</p>}</div></div></section>
          <section className="detail-section" aria-labelledby="value-title"><SectionHeading title="Value and validation" detail="A measurable experiment, without fabricated savings." /><div className="callout"><h3>Measure this</h3><p>{opportunity.measurableOutcome}</p></div><h3>Next validation step</h3><p>{opportunity.nextValidationStep}</p><h3>What must be true</h3>{hypothesis.assumptions.length ? <ul className="unknown-list">{hypothesis.assumptions.map((assumption) => <li key={assumption}>{assumption}</li>)}</ul> : <p>No assumptions recorded.</p>}<h3>Questions to confirm</h3>{hypothesis.confirmationQuestions.length ? <ul className="unknown-list">{hypothesis.confirmationQuestions.map((question) => <li key={question}>{question}</li>)}</ul> : <p>No confirmation questions recorded.</p>}</section>
        </div>
        <aside className="detail-aside">
          <section className="panel panel-dark"><div className="panel-header"><div><h2>Recommendation state</h2><p>Human review is the release gate.</p></div><Icon name="shield" size={18} /></div><div className="panel-body"><div className="inline-meta"><StatusBadge value={gate?.passed ? "gate passed" : "gate rejected"} tone={gate?.passed ? "success" : "danger"} /><StatusBadge value={opportunity.rankingConfidence} tone="info" /></div><div className="dark-score">{scorecard ? <><strong>{scorecard.totalScore}</strong><span>/ 100</span></> : <><strong>--</strong><span>not scored</span></>}</div><p className="dark-copy">{gate?.passed ? "This proposal can be ranked, but its assumptions still need a human check." : `This proposal is preserved but held by: ${gate?.failureCodes.join(", ") || "an incomplete gate"}.`}</p></div></section>
          <section className="detail-section" aria-labelledby="review-title"><SectionHeading title="Record a decision" detail="This creates a new history entry." /><ReviewForm opportunityId={opportunity.id} currentDecision={currentDecision} /></section>
          {scorecard && <section className="detail-section" aria-labelledby="score-title"><SectionHeading title="Score breakdown" detail={`Rubric ${scorecard.rubricVersion}`} /><div className="score-grid">{Object.entries(scorecard.dimensionValues).map(([key, value]) => { const max = opportunityWeights[key as keyof typeof opportunityWeights] ?? 1; const weighted = (value / 4) * max; return <div className="score-row" key={key}><div className="score-row-head"><strong>{dimensionLabels[key] ?? key}</strong><span>{value} / 4 · {weighted.toFixed(1)} pts</span></div><div className="score-bar"><span style={{ width: `${(value / 4) * 100}%` }} /></div><p>{scorecard.dimensionRationales[key] ?? "No rationale recorded."}</p></div>; })}</div></section>}
          <section className="detail-section" aria-labelledby="access-title"><SectionHeading title="Buildability" detail="The access boundary is explicit." /><span className="queue-label">Buildability</span><div className="inline-meta"><StatusBadge value={opportunity.buildability} tone={opportunity.buildability === "high" ? "success" : "warning"} /><EpistemicLabel type={opportunity.evidenceStrength === "high" ? "verified" : "inferred"} /></div><h3>Integrations</h3>{opportunity.requiredIntegrations.length ? <div className="tag-row">{opportunity.requiredIntegrations.map((item) => <span className="tag" key={item}>{item}</span>)}</div> : <p>None specified.</p>}<h3>Private access required</h3>{opportunity.requiredPrivateAccess.length ? <div className="tag-row">{opportunity.requiredPrivateAccess.map((item) => <span className="tag" key={item}>{item}</span>)}</div> : <p>None specified.</p>}<h3>Risks</h3>{opportunity.risks.length ? <ul className="unknown-list">{opportunity.risks.map((risk) => <li key={risk}>{risk}</li>)}</ul> : <p>No risks recorded.</p>}</section>
          {dossier?.sources.length ? <section className="detail-section"><SectionHeading title="Source trail" detail={`${dossier.sources.length} dossier sources`} /><div className="source-list">{dossier.sources.map((source) => <SourceCitation key={source.id} url={source.canonicalUrl} title={source.title} tier={source.sourceTier} fetchedAt={source.fetchedAt} stale={isStale(source.fetchedAt)} />)}</div></section> : null}
        </aside>
      </div>
    </main>
  );
}
